// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oovybzqxuwvhimlaxhsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vdnlienF4dXd2aGltbGF4aHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjQ5NzgsImV4cCI6MjA1Njk0MDk3OH0.EZx2Zsl8Z0SWN99-ZrTx6Mb8gEnRX3huMczdXqZkE10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);